#define YY_DEFAULT_ACTION ECHO;
/* A lexical scanner generated by flex */

#define YY_END_TOK 0
#define YY_NEW_FILE -1
#define YY_DO_DEFAULT -2
#ifndef BUFSIZ
#include <stdio.h>
#endif
#define F_BUFSIZ 128
#define YY_BUF_SIZE (F_BUFSIZ * 2)
#define YY_BUF_MAX (YY_BUF_SIZE - 1)
#ifndef YY_MAX_LINE
#define YY_MAX_LINE F_BUFSIZ
#endif
#define YY_BUF_LIM (YY_BUF_MAX - YY_MAX_LINE)
#define ECHO fputs(yytext, yyout)
#define YY_INPUT(buf,result,max_size) \
	if (fgets(buf, max_size, yyin) != NULL) \
	    result = strlen(buf); \
	else if (!ferror(yyin)) \
	    result = YY_NULL; \
	else \
	    YY_FATAL_ERROR("fgets() in flex scanner failed");
#define YY_NULL 0
#define YY_OUTPUT(c) fputc(c, yyout);
#define YY_FATAL_ERROR(msg) \
	{ \
	fputs(msg, stderr); \
	putc('\n', stderr); \
	exit(1); \
	}
#define YY_FIRST_CHAR yy_ch_buf[yy_b_buf_p]
#define yywrap() 1
#define BEGIN yy_start = 1 +
#define YY_SET_BOL(array,pos) array[pos - 1] = '\n';
#define YY_DECL int yylex()
#define yyless(n) \
	{ \
	YY_DO_BEFORE_SCAN; \
	yy_c_buf_p = yy_b_buf_p + (n) - 1; \
	YY_DO_BEFORE_ACTION; \
	}
#define YY_BREAK break;
#define YY_INIT \
	{ \
	yyleng = yy_c_buf_p = yy_e_buf_p = 0; \
	yy_hold_char = yy_ch_buf[yy_c_buf_p] = '\n'; \
	yytext = &yy_ch_buf[yy_c_buf_p]; \
	yy_saw_eof = 0; \
	}
#define YY_LENG (yy_c_buf_p - yy_b_buf_p + 1)
#define YY_DO_BEFORE_SCAN \
	yytext[yyleng] = yy_hold_char;
#define YY_DO_BEFORE_ACTION \
	yytext = &yy_ch_buf[yy_b_buf_p]; \
	yyleng = YY_LENG; \
	yy_hold_char = yytext[yyleng]; \
	yytext[yyleng] = '\0';
#define REJECT \
        { \
	YY_DO_BEFORE_SCAN; \
	yy_c_buf_p = yy_full_match; \
        ++yy_lp; \
        goto find_rule; \
        }

static int input(void);
static void unput(char);

# line 1 "lexer.l"
#define __INITIAL 0
# line 2 "lexer.l"
#define OBTENER_TOKEN yylex
#define YY_INPUT(buf,result,max_size) \
{ \
int c = caracter(); \
result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
}
#define F_BUFSIZ 1024
FILE *incl;
char arch_incl[64];
# line 23 "lexer.l"
#define YY_JAM 113
#define YY_JAM_BASE 1055
static char a[180] =
    {   0,
       16,   16,   56,   57,    1,   56,   57,   54,   57,   56,
       57,   56,   57,   16,   56,   57,   56,   57,   21,   38,
       56,   57,   36,   56,   57,   18,   56,   57,   19,   56,
       57,   27,   56,   57,   23,   56,   57,   40,   56,   57,
       24,   56,   57,    8,   56,   57,   28,   56,   57,   52,
       56,   57,   56,   57,   56,   57,   30,   56,   57,   39,
       56,   57,   32,   56,   57,   56,   57,   51,   56,   57,
        9,   56,   57,   29,   56,   57,   10,   56,   57,   22,
       56,   57,   51,   56,   57,   51,   56,   57,   51,   56,
       57,   51,   56,   57,   51,   56,   57,   51,   56,   57,

       51,   56,   57,   51,   56,   57,   11,   56,   57,   37,
       56,   57,   12,   56,   57,   55,   56,   57,    1,   35,
       53,   16,   50,   25,   26,   20,   52,   13,   14,    2,
       31,   34,   33,    3,   17,   51,   15,   51,   51,   45,
       51,   51,   51,   46,   51,   51,   51,   51,   50,   51,
       51,   51,   51,   51,   51,   51,   51,   41,   51,   48,
       51,   49,   51,   51,   47,   51,   51,    7,    5,    6,
        4,   51,   51,   44,   51,   42,   51,   43,   51
    } ;

static short int l[115] =
    {   0,
       -2,   -2,    3,    5,    8,   10,   12,   14,   17,   19,
       23,   26,   29,   32,   35,   38,   41,   44,   47,   50,
       53,   55,   57,   60,   63,   66,   68,   71,   74,   77,
       80,   83,   86,   89,   92,   95,   98,  101,  104,  107,
      110,  113,  116,  119,  120,  121,  121,  122,  123,  123,
      123,  123,  123,  124,  125,  126,  127,  128,  128,  129,
      129,  130,  131,  132,  133,  134,  135,  135,  136,  137,
      137,  138,  139,  140,  142,  143,  144,  146,  147,  148,
      149,  149,  149,  149,  149,  150,  151,  152,  153,  154,
      155,  156,  157,  157,  157,  157,  157,  158,  160,  162,

      164,  165,  167,  168,  169,  170,  171,  172,  173,  174,
      176,  178,  180,  180
    } ;

static short int b[122] =
    {   0,
        0,    0, 1055,  119, 1055,  308,  334,   94,    0, 1055,
     1055, 1055, 1055, 1055,  324, 1055,   85, 1055, 1055,   83,
      308,  201,   81,  147,   82,  199,    0,  115, 1055, 1055,
     1055,   28,   96,   97,   93,  101,  101,   97,   96, 1055,
     1055, 1055, 1055,  137, 1055,  165, 1055,  163,   87,   84,
       81,   95,    0, 1055, 1055, 1055,  104,  133, 1055,  180,
     1055, 1055, 1055, 1055, 1055, 1055,  179, 1055,    0,   95,
     1055,   85,   70,    0,   70,   68,    0,   67,   81,   76,
       80,   69,   70,   63,    0,   74,   74,   73,   62,   55,
       61,   62,  133,  132,  131,  130,   63,    0,    0,    0,

       49,    0,   61, 1055, 1055, 1055, 1055,   36,   38,    0,
        0,    0, 1055,  212,  275,  397,  524,  651,  731,  853,
      933
    } ;

static short int d[122] =
    {   0,
      113,    1,  113,  113,  113,  113,  114,  113,  115,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      116,  117,  113,  113,  113,  118,  119,  120,  113,  113,
      113,  119,  119,  119,  119,  119,  119,  119,  119,  113,
      113,  113,  113,  113,  113,  114,  113,  113,  113,  113,
      113,  113,  121,  113,  113,  113,  113,  116,  113,  117,
      113,  113,  113,  113,  113,  113,  118,  113,  119,  120,
      113,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      113,  113,  113,  113,  121,  119,  119,  119,  119,  119,
      119,  119,  113,  113,  113,  113,  119,  119,  119,  119,

      119,  119,  119,  113,  113,  113,  113,  119,  119,  119,
      119,  119,-32767,  113,  113,  113,  113,  113,  113,  113,
      113
    } ;

static short int n[1183] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    4,    5,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    4,    6,    7,    8,    9,   10,   11,    3,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    3,   26,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,   29,   30,   31,   27,    3,   27,   32,   27,   33,

       34,   27,   35,   27,   36,   27,   27,   27,   27,   27,
       27,   27,   27,   37,   27,   38,   27,   27,   39,   27,
       27,   27,   40,   41,   42,   43,    3,   44,   48,   55,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       62,   63,   65,   66,   72,   44,   56,  112,   73,  111,
       44,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,  110,  109,  108,  107,  106,  105,  104,   44,  103,
      102,  101,  100,   99,   98,   97,   96,   95,   94,   93,
       92,   91,   90,   89,   88,   87,   86,   71,   68,   61,
       59,   84,   83,   82,   49,   50,   81,   48,   47,   80,

       79,   78,   77,   76,   75,   51,   74,   71,   68,   64,
       61,   52,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   59,   54,   47,   45,   53,
      113,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,

       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,

       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,  113,  113,
      113,  113,  113,  113,  113,   69,   69,   69,   69,   69,

       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,  113,  113,  113,  113,   69,  113,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,

       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
      113,  113,  113,  113,  113,  113,  113,   85,   85,   85,

       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,  113,  113,  113,  113,   85,  113,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,

      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113
    } ;

static short int c[1183] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    8,   17,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       23,   23,   25,   25,   32,   44,   17,  109,   32,  108,
        4,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,  103,  101,   97,   96,   95,   94,   93,   44,   92,
       91,   90,   89,   88,   87,   86,   84,   83,   82,   81,
       80,   79,   78,   76,   75,   73,   72,   70,   67,   60,
       58,   52,   51,   50,    8,    8,   49,   48,   46,   39,

       38,   37,   36,   35,   34,    8,   33,   28,   26,   24,
       22,    8,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,

      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,   21,   15,    7,    6,  115,
        0,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  116,  116,  116,

      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,

      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,

      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,

      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,    0,    0,
        0,    0,    0,    0,    0,  119,  119,  119,  119,  119,

      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,    0,    0,    0,    0,  119,    0,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,

      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
        0,    0,    0,    0,    0,    0,    0,  121,  121,  121,

      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,    0,    0,    0,    0,  121,    0,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,

      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113
    } ;


FILE *yyin = stdin, *yyout = stdout;
static int yy_start, yy_b_buf_p, yy_c_buf_p, yy_e_buf_p;
static int yy_saw_eof = 1, yy_init = 1;
static char yy_ch_buf[YY_BUF_SIZE + 1];
static int yy_st_buf[YY_BUF_SIZE];
static char yy_hold_char;
char *yytext;
int yyleng;

static int input(void)
{
  int c;

  YY_DO_BEFORE_SCAN
  if (yy_c_buf_p == yy_e_buf_p) {
    int yy_n_chars;

    if (yy_saw_eof) {
      if (yywrap())
	 return (EOF);

      YY_INIT;
    }

    yy_b_buf_p = 0;
    YY_INPUT(yy_ch_buf, yy_n_chars, YY_MAX_LINE);

    if (yy_n_chars == YY_NULL) {
      yy_saw_eof = 1;

      if (yywrap())
	return (EOF);

      YY_INIT;
      return (input());
    }

    yy_c_buf_p = -1;
    yy_e_buf_p = yy_n_chars - 1;
  }

  c = yy_ch_buf[++yy_c_buf_p];

  YY_DO_BEFORE_ACTION;

  return (c);
}


static void unput(char c)
{
    YY_DO_BEFORE_SCAN;

    if (yy_c_buf_p == 0) {
	register int i;
	register int yy_buf_pos = YY_BUF_MAX;

	for (i = yy_e_buf_p; i >= yy_c_buf_p; --i) {
	    yy_ch_buf[yy_buf_pos] = yy_ch_buf[i];
	    yy_st_buf[yy_buf_pos] = yy_st_buf[i];
	    --yy_buf_pos;
	}

	yy_c_buf_p = YY_BUF_MAX - yy_e_buf_p;
	yy_e_buf_p = YY_BUF_MAX;
    }

    if (yy_c_buf_p <= 0)
	YY_FATAL_ERROR("flex scanner push-back overflow");

    if (yy_c_buf_p >= yy_b_buf_p && yy_ch_buf[yy_c_buf_p] == '\n')
	yy_ch_buf[yy_c_buf_p - 1] = '\n';

    yy_ch_buf[yy_c_buf_p--] = c;

    YY_DO_BEFORE_ACTION;
}


YY_DECL
{
  register int yy_curst;
  register char yy_sym;
  int yy_n_chars, yy_lp, yy_iii, yy_buf_pos, yy_act, yy_full_match;




  if (yy_init) {
    YY_INIT;
    yy_start = 1;
    yy_init = 0;
  }
  goto get_next_token;

do_action:
  yy_full_match = yy_c_buf_p;

  for ( ; ; )	{
    YY_DO_BEFORE_ACTION

    switch (yy_act) {
case 1:
# line 25 "lexer.l"
{}
	YY_BREAK
case 2:
# line 27 "lexer.l"
return NOMBRE_IZQ;
	YY_BREAK
case 3:
# line 28 "lexer.l"
return NOMBRE_DER;
	YY_BREAK
case 4:
# line 30 "lexer.l"
return DECL_VARS;
	YY_BREAK
case 5:
# line 31 "lexer.l"
return DECL_FUNC;
	YY_BREAK
case 6:
# line 32 "lexer.l"
return DECL_PPAL;
	YY_BREAK
case 7:
# line 33 "lexer.l"
return DECL_FIN;
	YY_BREAK
case 8:
# line 36 "lexer.l"
return PUNTO;
	YY_BREAK
case 9:
# line 37 "lexer.l"
return BLOQUE_IZQ;
	YY_BREAK
case 10:
# line 38 "lexer.l"
return BLOQUE_DER;
	YY_BREAK
case 11:
# line 39 "lexer.l"
return LLAVE_IZQ;
	YY_BREAK
case 12:
# line 40 "lexer.l"
return LLAVE_DER;
	YY_BREAK
case 13:
# line 41 "lexer.l"
{}//COMENTARIO;
	YY_BREAK
case 14:
# line 42 "lexer.l"
{}//COMENTARIO;
	YY_BREAK
case 15:
# line 43 "lexer.l"
{yytext[yyleng-1]=0;
				OUT(SALIDA1,"\n%s\n",yytext+1);}//ASEMBLER;
	YY_BREAK
case 16:
# line 45 "lexer.l"
{}//SEPARADOR;
	YY_BREAK
case 17:
# line 46 "lexer.l"
{
							yytext[yyleng-2]=0;
							sprintf(arch_incl,"%slib\\%s",directorio_actual,yytext+1);
                     incl=fopen(arch_incl,"r+");
                     if(incl==NULL)
                     {
                     	printf("No se pudo encontrar el archivo '%s'",yytext+1);
                        exit(1);
                     }
                     incluir(SALIDA1,incl);
						}
	YY_BREAK
case 18:
# line 58 "lexer.l"
return PAR_IZQ;
	YY_BREAK
case 19:
# line 59 "lexer.l"
return PAR_DER;
	YY_BREAK
case 20:
# line 60 "lexer.l"
return D_FUNC;
	YY_BREAK
case 21:
# line 61 "lexer.l"
return D_VECT;
	YY_BREAK
case 22:
# line 63 "lexer.l"
return NEGAC;
	YY_BREAK
case 23:
# line 64 "lexer.l"
return SUMA;
	YY_BREAK
case 24:
# line 65 "lexer.l"
return RESTA;
	YY_BREAK
case 25:
# line 66 "lexer.l"
return MASMAS;
	YY_BREAK
case 26:
# line 67 "lexer.l"
return MENMEN;
	YY_BREAK
case 27:
# line 69 "lexer.l"
return MULT;
	YY_BREAK
case 28:
# line 70 "lexer.l"
return DIV;
	YY_BREAK
case 29:
# line 71 "lexer.l"
return MOD;
	YY_BREAK
case 30:
# line 73 "lexer.l"
return MEN_Q;
	YY_BREAK
case 31:
# line 74 "lexer.l"
return MEN_IG;
	YY_BREAK
case 32:
# line 75 "lexer.l"
return MAY_Q;
	YY_BREAK
case 33:
# line 76 "lexer.l"
return MAY_IG;
	YY_BREAK
case 34:
# line 78 "lexer.l"
return IG_QUE;
	YY_BREAK
case 35:
# line 79 "lexer.l"
return DIF_QUE;
	YY_BREAK
case 36:
# line 81 "lexer.l"
return AND;
	YY_BREAK
case 37:
# line 82 "lexer.l"
return OR;
	YY_BREAK
case 38:
# line 83 "lexer.l"
return XOR;
	YY_BREAK
case 39:
# line 85 "lexer.l"
return IGUAL;
	YY_BREAK
case 40:
# line 86 "lexer.l"
return COMA;
	YY_BREAK
case 41:
# line 88 "lexer.l"
return INTEGER;
	YY_BREAK
case 42:
# line 89 "lexer.l"
return BUFFER;
	YY_BREAK
case 43:
# line 90 "lexer.l"
return RETORNO;
	YY_BREAK
case 44:
# line 91 "lexer.l"
return WHILE;
	YY_BREAK
case 45:
# line 92 "lexer.l"
return DO;
	YY_BREAK
case 46:
# line 93 "lexer.l"
return IF;
	YY_BREAK
case 47:
# line 94 "lexer.l"
return THEN;
	YY_BREAK
case 48:
# line 95 "lexer.l"
return ELSE;
	YY_BREAK
case 49:
# line 96 "lexer.l"
return GOTO;
	YY_BREAK
case 50:
# line 98 "lexer.l"
{/*if(buscar_simbolo(yytext)==NULL)ingresar_simbolo(IDENT,yytext);*/
				strcpy(ult_s->atr,yytext+1);
				ult_s->id=IDENT;
				return IDENT;}
	YY_BREAK
case 51:
# line 103 "lexer.l"
{strcat(yytext,"_");
				if(buscar_simbolo(yytext)==NULL)ingresar_simbolo(IDENT,yytext);
				strcpy(ult_s->atr,yytext);
				ult_s->id=IDENT;
				return IDENT;}
	YY_BREAK
case 52:
# line 109 "lexer.l"
{/*if(buscar_simbolo(yytext)==NULL)ingresar_simbolo(NUMERO,yytext);*/
				strcpy(ult_s->atr,yytext);
				ult_s->id=NUMERO;
				return NUMERO;}
	YY_BREAK
case 53:
# line 113 "lexer.l"
return CADENA;
	YY_BREAK
case 54:
# line 115 "lexer.l"
{/*linea++;*/}
	YY_BREAK
case 55:
# line 117 "lexer.l"
{printf("Caracter desconocido en la linea #%d.\n",linea);exit(1);}
	YY_BREAK
case 56:
# line 119 "lexer.l"
{if(*yytext!=13){printf("Lexema no valido en la linea #%d: %c\n",linea,*yytext);exit(1);}}
	YY_BREAK
case 57:
# line 121 "lexer.l"
YY_DEFAULT_ACTION;
	YY_BREAK

    case YY_NEW_FILE:
      break;
    case YY_END_TOK:
      return (YY_END_TOK);
    default:
      YY_FATAL_ERROR("fatal flex scanner internal error");
    }

get_next_token:
    YY_DO_BEFORE_SCAN

    yy_curst = yy_start;

    if (yy_ch_buf[yy_c_buf_p] == '\n')
      ++yy_curst;

    yy_b_buf_p = yy_c_buf_p + 1;

    do {
      if (yy_c_buf_p == yy_e_buf_p) {
	if (yy_e_buf_p >= YY_BUF_LIM) {
	  yy_n_chars = yy_e_buf_p - yy_b_buf_p;

	  if (yy_n_chars >= 0) {
	    for (yy_iii = 0; yy_iii <= yy_n_chars; ++yy_iii) {
	      yy_buf_pos = yy_b_buf_p + yy_iii;
	      yy_ch_buf[yy_iii] = yy_ch_buf[yy_buf_pos];
	      yy_st_buf[yy_iii] = yy_st_buf[yy_buf_pos];
	    }
	  }

	  yy_b_buf_p = 0;
	  yy_e_buf_p = yy_n_chars;

	  if (yy_e_buf_p >= YY_BUF_LIM)
	    YY_FATAL_ERROR("flex input buffer overflowed");

	    yy_c_buf_p = yy_e_buf_p;
	  } else if (yy_saw_eof) {
saweof:		
	  if (yy_b_buf_p <= yy_e_buf_p)
	    break;
	  if (yywrap())
	    yy_act = YY_END_TOK;
	  else {
	    YY_INIT;
	    yy_act = YY_NEW_FILE;
	  }
	  goto do_action;
	}

	YY_INPUT((yy_ch_buf + yy_c_buf_p + 1), yy_n_chars, YY_MAX_LINE);

	if (yy_n_chars == YY_NULL) {
	  if (yy_saw_eof)
	    YY_FATAL_ERROR("flex scanner saw EOF twice - shouldn't happen");
	  yy_saw_eof = 1;
	  goto saweof;
	}

	yy_e_buf_p += yy_n_chars;
      }

      ++yy_c_buf_p;
      yy_sym = yy_ch_buf[yy_c_buf_p];

      while (c[b[yy_curst] + yy_sym] != yy_curst)
	yy_curst = d[yy_curst];

      yy_curst = n[b[yy_curst] + yy_sym];
      yy_st_buf[yy_c_buf_p] = yy_curst;

    } while (b[yy_curst] != YY_JAM_BASE);

    if (yy_c_buf_p >= yy_b_buf_p) {
      yy_curst = yy_st_buf[yy_c_buf_p];
      yy_lp = l[yy_curst];

find_rule:
      for ( ; ; ) {
	if (yy_lp && yy_lp < l[yy_curst + 1]) {
	  yy_act = a[yy_lp];
	  goto do_action;
	}

	if (--yy_c_buf_p < yy_b_buf_p)
	  break;

	yy_curst = yy_st_buf[yy_c_buf_p];
	yy_lp = l[yy_curst];
      }
    }
    ++yy_c_buf_p;

    yy_act = YY_DO_DEFAULT;
  }
}
# line 121 "lexer.l"

